-- OCR Dashboard Power Query 

-- Append queries from Y3Master.xlsx and Y4Master.xlsx datasets together
-- Create new query called "Clinical Relations Dashboard"

let
    Source = Table.Combine({#"Y3 Master", #"Y4 Master"}),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Approximately how much of the content and training for this course was provided by ... assigned preceptor (listed above)?", Percentage.Type}}),
    #"Divided Column" = Table.TransformColumns(#"Changed Type", {{"Approximately how much of the content and training for this course was provided by ... assigned preceptor (listed above)?", each _ / 100, Percentage.Type}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Divided Column",{{"Approximately how much of the content and training for this course was provided by ... other veterinarian(s)?", Percentage.Type}}),
    #"Divided Column1" = Table.TransformColumns(#"Changed Type1", {{"Approximately how much of the content and training for this course was provided by ... other veterinarian(s)?", each _ / 100, Percentage.Type}}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Divided Column1",{{"Approximately how much of the content and training for this course was provided by ... resident(s)?", Percentage.Type}}),
    #"Divided Column2" = Table.TransformColumns(#"Changed Type2", {{"Approximately how much of the content and training for this course was provided by ... resident(s)?", each _ / 100, Percentage.Type}}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Divided Column2",{{"Approximately how much of the content and training for this course was provided by ... intern(s)?", Percentage.Type}}),
    #"Divided Column3" = Table.TransformColumns(#"Changed Type3", {{"Approximately how much of the content and training for this course was provided by ... intern(s)?", each _ / 100, Percentage.Type}}),
    #"Changed Type4" = Table.TransformColumnTypes(#"Divided Column3",{{"Approximately how much of the content and training for this course was provided by ... RVT, LVT, or other technician(s)?", Percentage.Type}}),
    #"Divided Column4" = Table.TransformColumns(#"Changed Type4", {{"Approximately how much of the content and training for this course was provided by ... RVT, LVT, or other technician(s)?", each _ / 100, Percentage.Type}}),
    #"Changed Type5" = Table.TransformColumnTypes(#"Divided Column4",{{"Approximately how much of the content and training for this course was provided by ... graduate student(s)?", Percentage.Type}}),
    #"Divided Column5" = Table.TransformColumns(#"Changed Type5", {{"Approximately how much of the content and training for this course was provided by ... graduate student(s)?", each _ / 100, Percentage.Type}}),
    #"Changed Type6" = Table.TransformColumnTypes(#"Divided Column5",{{"Approximately how much of the content and training for this course was provided by ... other(s)?", Percentage.Type}}),
    #"Divided Column6" = Table.TransformColumns(#"Changed Type6", {{"Approximately how much of the content and training for this course was provided by ... other(s)?", each _ / 100, Percentage.Type}}),
    #"Changed Type7" = Table.TransformColumnTypes(#"Divided Column6",{{"Total (must equal 100%)", Percentage.Type}}),
    #"Divided Column7" = Table.TransformColumns(#"Changed Type7", {{"Total (must equal 100%)", each _ / 100, Percentage.Type}}),
    #"Changed Type8" = Table.TransformColumnTypes(#"Divided Column7",{{"Approximately how much of the content and training for this course was provided by ... WesternU faculty (e.g., course leader, instructor, guest speaker)?", Percentage.Type}}),
    #"Divided Column8" = Table.TransformColumns(#"Changed Type8", {{"Approximately how much of the content and training for this course was provided by ... WesternU faculty (e.g., course leader, instructor, guest speaker)?", each _ / 100, Percentage.Type}}),
    #"Changed Type9" = Table.TransformColumnTypes(#"Divided Column8",{{"How much of the relevant learning and training for this rotation was provided by Assigned preceptor (listed above)", Percentage.Type}}),
    #"Divided Column9" = Table.TransformColumns(#"Changed Type9", {{"How much of the relevant learning and training for this rotation was provided by Assigned preceptor (listed above)", each _ / 100, Percentage.Type}}),
    #"Changed Type10" = Table.TransformColumnTypes(#"Divided Column9",{{"How much of the relevant learning and training for this rotation was provided by Other veterinarian(s)", Percentage.Type}}),
    #"Divided Column10" = Table.TransformColumns(#"Changed Type10", {{"How much of the relevant learning and training for this rotation was provided by Other veterinarian(s)", each _ / 100, Percentage.Type}}),
    #"Changed Type11" = Table.TransformColumnTypes(#"Divided Column10",{{"How much of the relevant learning and training for this rotation was provided by Resident(s)", Percentage.Type}}),
    #"Divided Column11" = Table.TransformColumns(#"Changed Type11", {{"How much of the relevant learning and training for this rotation was provided by Resident(s)", each _ / 100, Percentage.Type}}),
    #"Changed Type12" = Table.TransformColumnTypes(#"Divided Column11",{{"How much of the relevant learning and training for this rotation was provided by Intern(s)", Percentage.Type}}),
    #"Divided Column12" = Table.TransformColumns(#"Changed Type12", {{"How much of the relevant learning and training for this rotation was provided by Intern(s)", each _ / 100, Percentage.Type}}),
    #"Changed Type13" = Table.TransformColumnTypes(#"Divided Column12",{{"How much of the relevant learning and training for this rotation was provided by RVT, LVT, or other technician(s)", Percentage.Type}}),
    #"Divided Column13" = Table.TransformColumns(#"Changed Type13", {{"How much of the relevant learning and training for this rotation was provided by RVT, LVT, or other technician(s)", each _ / 100, Percentage.Type}}),
    #"Changed Type14" = Table.TransformColumnTypes(#"Divided Column13",{{"How much of the relevant learning and training for this rotation was provided by Graduate student(s)", Percentage.Type}}),
    #"Divided Column14" = Table.TransformColumns(#"Changed Type14", {{"How much of the relevant learning and training for this rotation was provided by Graduate student(s)", each _ / 100, Percentage.Type}}),
    #"Changed Type15" = Table.TransformColumnTypes(#"Divided Column14",{{"How much of the relevant learning and training for this rotation was provided by Other(s)", Percentage.Type}}),
    #"Divided Column15" = Table.TransformColumns(#"Changed Type15", {{"How much of the relevant learning and training for this rotation was provided by Other(s)", each _ / 100, Percentage.Type}}),
    #"Added Custom" = Table.AddColumn(#"Divided Column15", "Physical Safety % (Faculty Site)", each [#"How frequently did the clinical site ... provide a physically safe learning environment, e.g., free of trip hazards, adequate exit signage? (Faculty)"] / 5),
    #"Changed Type16" = Table.TransformColumnTypes(#"Added Custom",{{"Physical Safety % (Faculty Site)", Percentage.Type}}),
    #"Added Custom1" = Table.AddColumn(#"Changed Type16", "Psychological Safety % (Faculty Site)", each [#"How frequently did the clinical site ... provide a psychologically safe learning environment, e.g., free of intimidation, free of humiliation? (Faculty)"] / 5),
    #"Changed Type17" = Table.TransformColumnTypes(#"Added Custom1",{{"Psychological Safety % (Faculty Site)", Percentage.Type}}),
    #"Added Custom2" = Table.AddColumn(#"Changed Type17", "DEI % (Faculty Site)", each [#"How frequently did the clinical site ... feel welcoming of diversity and including the domain of ethnicity, gender, age, thought, background, etc.? (Faculty)"] / 5),
    #"Changed Type18" = Table.TransformColumnTypes(#"Added Custom2",{{"DEI % (Faculty Site)", Percentage.Type}}),
    #"Added Custom3" = Table.AddColumn(#"Changed Type18", "Staff Orient % (Faculty Site)", each [#"How frequently did the clinical site ... staff orient you to the various aspects of the facility in order to acclimate you to the environment? (Faculty)"] / 5),
    #"Changed Type19" = Table.TransformColumnTypes(#"Added Custom3",{{"Staff Orient % (Faculty Site)", Percentage.Type}}),
    #"Added Custom4" = Table.AddColumn(#"Changed Type19", "Site Culture % (Faculty Site)", each [#"How frequently did the clinical site ... culture feel like it supported your learning? (Faculty)"] / 5),
    #"Changed Type20" = Table.TransformColumnTypes(#"Added Custom4",{{"Site Culture % (Faculty Site)", Percentage.Type}}),
    #"Added Custom5" = Table.AddColumn(#"Changed Type20", "Site Score", each [#"How frequently did the clinical site ... provide a physically safe learning environment, e.g., free of trip hazards, adequate exit signage?"]+[#"How frequently did the clinical site ... provide a psychologically safe learning environment, e.g., free of intimidation, free of humiliation?"]+[#"How frequently did the clinical site ... feel welcoming of diversity, including the domains of ethnicity, gender, age, thought, background, etc.?"]+[#"How frequently did the clinical site ... staff orient you to the various aspects of the facility in order to acclimate you to the environment?"]+[#"How frequently did the clinical site ... culture feel like it supported your learning?"]),
    #"Added Custom6" = Table.AddColumn(#"Added Custom5", "Site %", each [Site Score] / 25),
    #"Changed Type21" = Table.TransformColumnTypes(#"Added Custom6",{{"Site Score", Int64.Type}, {"Site %", Percentage.Type}}),
    #"Added Custom7" = Table.AddColumn(#"Changed Type21", "Preceptor Score", each [#"How frequently did your preceptor ... state the relevance of the rotation goals to you?"]+[#"How frequently did your preceptor ... offer you suggestions for improvement?"]+[#"How frequently did your preceptor ... listen to you?"]+[#"How frequently did your preceptor ... focus your activities to achieve the rotation goals?"]+[#"How frequently did your preceptor ... evaluate your ability to analyze and synthesize knowledge, e.g., lab results, medical records?"]+[#"How frequently did your preceptor ... motivate you to learn on your own?"]+[#"How frequently did your preceptor ... encourage you to do outside reading, e.g., textbooks, articles?"]+[#"How frequently did your preceptor ... state the rotation goals clearly and concisely?"]+[#"How frequently did your preceptor ... give you feedback on your knowledge and performance?"]+[#"How frequently did your preceptor ... explicitly encourage further learning?"]+[#"How frequently did your preceptor ... evaluate your ability to apply your knowledge to specific patients or situations?"]+[#"How frequently did your preceptor ... encourage you to actively participate in discussion?"]+[#"How frequently did your preceptor ... evaluate your knowledge of factual medical or discipline related information?"]+[#"How frequently did your preceptor ... prioritize the rotation goals?"]+[#"How frequently did your preceptor ... give you corrective (negative) feedback?"]+[#"How frequently did your preceptor ... maintain focus on learning and avoided excessive digressions?"]+[#"How frequently did your preceptor ... evaluate your medical skills as they apply to specific patients or situations?"]+[#"How frequently did your preceptor ... model and call attention to time management, balancing teaching, patient care, and record keeping?"]+[#"How frequently did your preceptor ... encourage you to bring up issues and problems?"]+[#"How frequently did your preceptor ... explain why you were correct or incorrect?"]+[#"How frequently did your preceptor ... express and demonstrate respect for you?"]+[#"How frequently did your preceptor ... discourage external interruptions that were not related to the learning objectives?"]+[#"How frequently did your preceptor ... provide you with an opportunity to practice hands on clinical or discipline relevant skills?"]),
    #"Added Custom8" = Table.AddColumn(#"Added Custom7", "Preceptor %", each [Preceptor Score] / 115),
    #"Changed Type22" = Table.TransformColumnTypes(#"Added Custom8",{{"Preceptor Score", Int64.Type}, {"Preceptor %", Percentage.Type}}),
    #"Added Custom9" = Table.AddColumn(#"Changed Type22", "Rotation Score", each [#"How frequently did the... rotation syllabus provide clear and relevant information?"]+[#"How frequently did the... learning objectives provide a clear guide to help focus your engagement in learning activities?"]+[#"How frequently did the... rotation leader respond in a timely manner when contacted?"]+[#"How frequently did the... rotation assignments. e.g., SOAPS, rounds, papers, case reflections, help you to achieve the learning objectives?"]),
    #"Added Custom10" = Table.AddColumn(#"Added Custom9", "Rotation %", each [Rotation Score] / 20),
    #"Added Custom11" = Table.AddColumn(#"Added Custom10", "Physical Safe %", each [#"How frequently did the clinical site ... provide a physically safe learning environment, e.g., free of trip hazards, adequate exit signage?"] / 5),
    #"Changed Type23" = Table.TransformColumnTypes(#"Added Custom11",{{"Physical Safe %", Percentage.Type}}),
    #"Added Custom12" = Table.AddColumn(#"Changed Type23", "Psychologically Safe %", each [#"How frequently did the clinical site ... provide a psychologically safe learning environment, e.g., free of intimidation, free of humiliation?"] / 5),
    #"Changed Type24" = Table.TransformColumnTypes(#"Added Custom12",{{"Psychologically Safe %", Percentage.Type}}),
    #"Added Custom13" = Table.AddColumn(#"Changed Type24", "DEI %", each [#"How frequently did the clinical site ... feel welcoming of diversity, including the domains of ethnicity, gender, age, thought, background, etc.?"] / 5),
    #"Changed Type25" = Table.TransformColumnTypes(#"Added Custom13",{{"DEI %", Percentage.Type}}),
    #"Added Custom14" = Table.AddColumn(#"Changed Type25", "Staff Orient %", each [#"How frequently did the clinical site ... staff orient you to the various aspects of the facility in order to acclimate you to the environment?"] / 5),
    #"Changed Type26" = Table.TransformColumnTypes(#"Added Custom14",{{"Staff Orient %", Percentage.Type}}),
    #"Added Custom15" = Table.AddColumn(#"Changed Type26", "Site Culture %", each [#"How frequently did the clinical site ... culture feel like it supported your learning?"] / 5),
    #"Changed Type27" = Table.TransformColumnTypes(#"Added Custom15",{{"Site Culture %", Percentage.Type}}),
    #"Added Custom16" = Table.AddColumn(#"Changed Type27", "Rotation Syllabus %", each [#"How frequently did the... rotation syllabus provide clear and relevant information?"] / 5),
    #"Changed Type28" = Table.TransformColumnTypes(#"Added Custom16",{{"Rotation Syllabus %", Percentage.Type}}),
    #"Added Custom17" = Table.AddColumn(#"Changed Type28", "Learning Objectives %", each [#"How frequently did the... learning objectives provide a clear guide to help focus your engagement in learning activities?"] / 5),
    #"Changed Type29" = Table.TransformColumnTypes(#"Added Custom17",{{"Learning Objectives %", Percentage.Type}}),
    #"Added Custom18" = Table.AddColumn(#"Changed Type29", "Rotation Leader %", each [#"How frequently did the... rotation leader respond in a timely manner when contacted?"] / 5),
    #"Changed Type30" = Table.TransformColumnTypes(#"Added Custom18",{{"Rotation Leader %", Percentage.Type}}),
    #"Added Custom19" = Table.AddColumn(#"Changed Type30", "Rotation Assignments %", each [#"How frequently did the... rotation assignments. e.g., SOAPS, rounds, papers, case reflections, help you to achieve the learning objectives?"] / 5),
    #"Changed Type31" = Table.TransformColumnTypes(#"Added Custom19",{{"Rotation Assignments %", Percentage.Type}}),
    #"Added Custom20" = Table.AddColumn(#"Changed Type31", "Y3 Total Score", each [Site Score]+[Preceptor Score]),
    #"Changed Type32" = Table.TransformColumnTypes(#"Added Custom20",{{"Y3 Total Score", Int64.Type}}),
    #"Added Custom21" = Table.AddColumn(#"Changed Type32", "Y3 Total Score %", each [Y3 Total Score] / 140),
    #"Changed Type33" = Table.TransformColumnTypes(#"Added Custom21",{{"Y3 Total Score %", Percentage.Type}}),
    #"Added Custom22" = Table.AddColumn(#"Changed Type33", "Y4 Total Score", each [Site Score]+[Preceptor Score]+[Rotation Score]),
    #"Changed Type34" = Table.TransformColumnTypes(#"Added Custom22",{{"Y4 Total Score", Int64.Type}}),
    #"Added Custom23" = Table.AddColumn(#"Changed Type34", "Y4 Total Score %", each [Y4 Total Score] / 160),
    #"Changed Type35" = Table.TransformColumnTypes(#"Added Custom23",{{"Y4 Total Score %", Percentage.Type}}),
    #"Replace Scoring values 0 to null" = Table.ReplaceValue(#"Changed Type35",0,null,Replacer.ReplaceValue,{"How frequently did the clinical site ... provide a physically safe learning environment, e.g., free of trip hazards, adequate exit signage? (Faculty)", "How frequently did the clinical site ... provide a psychologically safe learning environment, e.g., free of intimidation, free of humiliation? (Faculty)", "How frequently did the clinical site ... feel welcoming of diversity and including the domain of ethnicity, gender, age, thought, background, etc.? (Faculty)", "How frequently did the clinical site ... staff orient you to the various aspects of the facility in order to acclimate you to the environment? (Faculty)", "How frequently did the clinical site ... culture feel like it supported your learning? (Faculty)", "How frequently did your preceptor ... state the relevance of the rotation goals to you?", "How frequently did your preceptor ... offer you suggestions for improvement?", "How frequently did your preceptor ... listen to you?", "How frequently did your preceptor ... focus your activities to achieve the rotation goals?", "How frequently did your preceptor ... evaluate your ability to analyze and synthesize knowledge, e.g., lab results, medical records?", "How frequently did your preceptor ... motivate you to learn on your own?", "How frequently did your preceptor ... encourage you to do outside reading, e.g., textbooks, articles?", "How frequently did your preceptor ... state the rotation goals clearly and concisely?", "How frequently did your preceptor ... give you feedback on your knowledge and performance?", "How frequently did your preceptor ... explicitly encourage further learning?", "How frequently did your preceptor ... evaluate your ability to apply your knowledge to specific patients or situations?", "How frequently did your preceptor ... encourage you to actively participate in discussion?", "How frequently did your preceptor ... evaluate your knowledge of factual medical or discipline related information?", "How frequently did your preceptor ... prioritize the rotation goals?", "How frequently did your preceptor ... give you corrective (negative) feedback?", "How frequently did your preceptor ... maintain focus on learning and avoided excessive digressions?", "How frequently did your preceptor ... evaluate your medical skills as they apply to specific patients or situations?", "How frequently did your preceptor ... model and call attention to time management, balancing teaching, patient care, and record keeping?", "How frequently did your preceptor ... encourage you to bring up issues and problems?", "How frequently did your preceptor ... explain why you were correct or incorrect?", "How frequently did your preceptor ... express and demonstrate respect for you?", "How frequently did your preceptor ... discourage external interruptions that were not related to the learning objectives?", "How frequently did your preceptor ... provide you with an opportunity to practice hands on clinical or discipline relevant skills?", "How frequently did the clinical site ... provide a physically safe learning environment, e.g., free of trip hazards, adequate exit signage?", "How frequently did the clinical site ... provide a psychologically safe learning environment, e.g., free of intimidation, free of humiliation?", "How frequently did the clinical site ... feel welcoming of diversity, including the domains of ethnicity, gender, age, thought, background, etc.?", "How frequently did the clinical site ... staff orient you to the various aspects of the facility in order to acclimate you to the environment?", "How frequently did the clinical site ... culture feel like it supported your learning?", "How frequently did the... learning objectives provide a clear guide to help focus your engagement in learning activities?", "How frequently did the... rotation leader respond in a timely manner when contacted?", "How frequently did the... rotation assignments. e.g., SOAPS, rounds, papers, case reflections, help you to achieve the learning objectives?"})
in
    #"Replace Scoring values 0 to null"